AllCops:
  TargetRubyVersion: 2.6
  DisplayCopNames: true
  Exclude:
    - spec/**/*
    - vendor/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodName:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/EmptyWhen:
  Enabled: false

Style/MethodMissingSuper:
  Enabled: false

Style/MissingRespondToMissing:
  Enabled: false
