AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  Exclude:
    - spec/**/*
    - vendor/**/*

Layout/DotPosition:
  EnforcedStyle: trailing

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodName:
  Enabled: false

Metrics/LineLength:
  Max: 120

Lint/EmptyWhen:
  Enabled: false

Style/MethodMissing:
  Enabled: false
