# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: rfunk 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "rfunk"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Alex Falkowski"]
  s.date = "2014-03-08"
  s.description = "https://github.com/alexfalkowski/rfunk/blob/master/README.md"
  s.email = "alexrfalkowski@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    ".ruby-version",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/rfunk.rb",
    "lib/rfunk/attribute.rb",
    "lib/rfunk/either.rb",
    "lib/rfunk/failure.rb",
    "lib/rfunk/lazy.rb",
    "lib/rfunk/none.rb",
    "lib/rfunk/not_found_error.rb",
    "lib/rfunk/option.rb",
    "lib/rfunk/some.rb",
    "lib/rfunk/success.rb",
    "lib/rfunk/value.rb",
    "spec/rfunk/either/either_spec.rb",
    "spec/rfunk/immutable/attribute_class.rb",
    "spec/rfunk/immutable/attribute_spec.rb",
    "spec/rfunk/immutable/customer.rb",
    "spec/rfunk/lazy/lazy_spec.rb",
    "spec/rfunk/maybe/none_spec.rb",
    "spec/rfunk/maybe/some_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/alexfalkowski/rfunk"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "Functional Programming in Ruby"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ice_nine>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_runtime_dependency(%q<ice_nine>, [">= 0"])
    else
      s.add_dependency(%q<ice_nine>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<ice_nine>, [">= 0"])
    end
  else
    s.add_dependency(%q<ice_nine>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<ice_nine>, [">= 0"])
  end
end

