version: 2
jobs:
  build:
    docker:
      - image: alexfalkowski/ruby:2.7
    steps:
      - checkout
      - restore_cache:
          keys:
            - rfunk-ruby-cache-{{ checksum "Gemfile.lock" }}
            - rfunk-ruby-cache-
      - run: make dependencies
      - save_cache:
          key: rfunk-ruby-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: make specs
      - store_test_results:
          path: reports
      - run: make analysis
  release:
    docker:
      - image: alexfalkowski/release:1.0
    steps:
      - checkout
      - run: release.sh

workflows:
  version: 2
  rfunk:
    jobs:
      - build
      - release:
          requires:
            - build
          filters:
            branches:
              only: master
