version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6
        environment:
          BUNDLE_JOBS: "3"
          BUNDLE_PATH: vendor/bundle
          BUNDLE_RETRY: "3"
    steps:
      - checkout
      - restore_cache:
          keys:
            - rfunk-gem-cache-{{ checksum "Gemfile.lock" }}
            - rfunk-gem-cache-
      - run: make dependencies
      - save_cache:
          key: rfunk-gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: make specs
      - store_test_results:
          path: reports
      - run: make analysis
